### ISSUE TITLE
Can not run the project

### ISSUE THREAD

**Issue by esmailpour-hosein** [Tradeshift/elements#25]
After merge of #24 I can't run the project anymore. Can you take a look?

```

> tradeshift-elements@ start /Users/username/IdeaProjects/elements
> run-p watch server


> tradeshift-elements@ watch /Users/username/IdeaProjects/elements
> cross-env-shell lerna exec --parallel -- rollup -w -c=`pwd`/rollup.config.js


> tradeshift-elements@ server /Users/username/IdeaProjects/elements
> server start --watch

lerna notice cli v3.13.4
lerna info Executing command in 6 packages: "rollup -w -c=/Users/username/IdeaProjects/elements/rollup.config.js"
{"level":40,"time":1557403711872,"pid":74702,"hostname":"c02y60ksjgh8-c","msg":"Loading default server configuration","v":1}
{"level":30,"time":1557403711875,"pid":74702,"hostname":"c02y60ksjgh8-c","msg":"Defaulting to current directory: /Users/username/IdeaProjects/elements","v":1}
tester: [!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
tester: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
tester:     at validateString (internal/validators.js:125:11)
tester:     at Object.join (path.js:1036:7)
tester:     at Object.<anonymous> (/Users/username/IdeaProjects/elements/rollup.config.js:18:25)
tester:     at Module._compile (internal/modules/cjs/loader.js:799:30)
tester:     at Object.require.extensions..js (/Users/username/IdeaProjects/elements/node_modules/rollup/bin/rollup:1344:24)
tester:     at Module.load (internal/modules/cjs/loader.js:666:32)
tester:     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
tester:     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
tester:     at Module.require (internal/modules/cjs/loader.js:705:19)
tester:     at require (internal/modules/cjs/helpers.js:14:16)
lerna ERR! rollup -w -c=/Users/username/IdeaProjects/elements/rollup.config.js exited 1 in 'tester'
lerna ERR! rollup -w -c=/Users/username/IdeaProjects/elements/rollup.config.js stderr:
[!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1036:7)
    at Object.<anonymous> (/Users/username/IdeaProjects/elements/rollup.config.js:18:25)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.require.extensions..js (/Users/username/IdeaProjects/elements/node_modules/rollup/bin/rollup:1344:24)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)


lerna ERR! rollup -w -c=/Users/username/IdeaProjects/elements/rollup.config.js exited 1 in 'tester'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tradeshift-elements@ watch: `cross-env-shell lerna exec --parallel -- rollup -w -c=`pwd`/rollup.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tradeshift-elements@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2019-05-09T12_08_32_809Z-debug.log
ERROR: "watch" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tradeshift-elements@ start: `run-p watch server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tradeshift-elements@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2019-05-09T12_08_32_883Z-debug.log

Process finished with exit code 1

```

**Comment by esmailpour-hosein** [comment]
Clean checkout helped, thanks to @zdlm! 👍
